site_name: Work Notes
site_url: https://example.com/
theme: 
  name: material
  palette:
    primary: black
    scheme: slate

nav:
  - Life Insurance: Placeholder.md

  - Products:
    - Non-Participating:
      - Term Life: 1_PRODUCTS/0_TERM_LIFE.md
      - Whole Life: 1_PRODUCTS/1_WHOLE_LIFE.md
    - Participating:
      - Overview: 1_PRODUCTS/3_PARTICIPATING.md
    - Investment Linked:
      - Overview: 1_PRODUCTS/2_UNIT_LINKED.md
    - Universal Life:
      - Overview:  1_PRODUCTS/3_UNIVERSAL_LIFE/0_OVERVIEW.md
      - Traditional UL:  1_PRODUCTS/3_UNIVERSAL_LIFE/1_UL.md
      - Indexed UL:  1_PRODUCTS/3_UNIVERSAL_LIFE/2_IUL.md
    - Endowment: tbc.md
    - Annuities:
      - Overview: 1_PRODUCTS/5_ANNUITIES/0_OVERVIEW.md
      - Fixed: 1_PRODUCTS/5_ANNUITIES/1_FDA.md
      - Variable: 1_PRODUCTS/5_ANNUITIES/2_VA.md
      - Indexed: 1_PRODUCTS/5_ANNUITIES/3_IA.md
    - Health:
      - Overview: TBC.MD

  - Valuation: Placeholder.md
  - Solvency:
    - Risk Based Capital: 3_SOLVENCY/0_RISK_BASED_CAPITAL.md
  - Embedded Value: Placeholder.md
  - IFRS17: Placeholder.md
  - Distribution: Placeholder.md
  - Health Insurance: Placeholder.md
  - General Insurance: Placeholder.md

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_css:
  - config/extra.css

extra_javascript:
  - config/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js