site_name: Work Notes
site_url: https://example.com/
theme: 
  name: material
  palette:
    primary: black
    scheme: slate

nav:
  - Actuarial:
    - Actuarial Overview: 1_Actuarial/1_Actuarial_Overview.md
    - Credentialling Process: 1_Actuarial/2_Credentialling_Process.md
    - Career Advice: 1_Actuarial/3_Career_Advice.md
  - Insurance:
    - Insurance Overview: 2_Insurance/1_Insurance_Overview.md
    - Insurance Concepts: 2_Insurance/2_Insurance_Concepts.md
    - Insurance Stakeholders: 2_Insurance/3_Insurance_Stakeholders.md
  - Life Insurance:
    - Life Products: 3_Life_Insurance/1_Life_Products.md
    - Product Features: 3_Life_Insurance/2_Product_Features.md
    - Modelling: 3_Life_Insurance/3_Modelling.md
    - Valuation: 3_Life_Insurance/4_Life_Valuation.md
    - Statutory Reporting: 3_Life_Insurance/5_Statutory_Reporting.md
    - Management Reporting: 3_Life_Insurance/6_Management_Reporting.md
    - Financial Reporting: 3_Life_Insurance/7_Financial_Reporting.md
    - Experience Studies: 3_Life_Insurance/8_Experience_Studies.md
    - Expense Management: 3_Life_Insurance/9_Expense_Management.md
    - Par Fund Management: 3_Life_Insurance/10_Par_Fund_Management.md
  - Health Insurance:
    - Health Products: 4_Health_Insurance/1_Health_Products.md
  - Reinsurance:
      - Overview: 5_Reinsurance/1_Reinsurance_Overview.md

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_css:
  - config/extra.css

extra_javascript:
  - config/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js