site_name: Work Notes
site_url: https://example.com/
theme: 
  name: material
  palette:
    primary: black
    scheme: slate

nav:
  - Life Insurance: Placeholder.md

  - Products:
    - Non-Participating:
      - Term Life: 1_PRODUCTS/0_NONPAR/0_TERM_LIFE.md
      - Whole Life: 1_PRODUCTS/0_NONPAR/1_WHOLE_LIFE.md
    - Participating:
      - Par Overview: 1_PRODUCTS/3_PARTICIPATING.md
    - Universal Life:
      - UL Overview:  1_PRODUCTS/2_UNIVERSAL_LIFE/0_UL_OVERVIEW.md
      - Traditional UL:  1_PRODUCTS/2_UNIVERSAL_LIFE/1_UL.md
      - Indexed UL:  1_PRODUCTS/2_UNIVERSAL_LIFE/2_IUL.md
    - Unit Linked:
      - Unit Linked Overview: 1_PRODUCTS/3_UNIT_LINKED/0_UNIT_LINKED_OVERVIEW.md
    - Endowment: tbc.md
    - Annuities:
      - Ann Overview: 1_PRODUCTS/5_ANNUITIES/0_ANN_OVERVIEW.md
      - Fixed: 1_PRODUCTS/5_ANNUITIES/1_FDA.md
      - Variable: 1_PRODUCTS/5_ANNUITIES/2_VA.md
      - Indexed: 1_PRODUCTS/5_ANNUITIES/3_IA.md
    - Health:
      - Overview: Placeholder.md
  - Valuation:
    - Solvency:
      - Solvency Overview: 2_VALUATION/3_SOLVENCY/0_RBC_OVERVIEW.md
      - SG RBC2: 2_VALUATION/3_SOLVENCY/1_SG_RBC2.md
    - Embedded Value: Placeholder.md
    - IFRS17:
      - IFRS17 Overview: 2_VALUATION/3_IFRS17/0_IFRS17_OVERVIEW.md
  - Reinsurance:
    - RI Overview: 3_REINSURANCE/0_RI_OVERVIEW.md
    - Proportional: 3_REINSURANCE/1_PROPORTIONAL.md
  - Distribution: Placeholder.md
  - Experience Studies: Placeholder.md
  - Asset Liability Mgmt: Placeholder.md

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_css:
  - config/extra.css

extra_javascript:
  - config/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js