site_name: Work Notes
site_url: https://example.com/
theme: 
  name: material
  palette:
    primary: black
    scheme: slate

nav:
  - Life Insurance: Placeholder.md
  - Products:
    - Term: 1_PRODUCTS/0_TERM.md
    - Whole Life: 1_PRODUCTS/1_WHOLE_LIFE.md
    - Endowment: 1_PRODUCTS/2_ENDOWMENT.md
    - Participating: 1_PRODUCTS/3_PARTICIPATING.md
    - Universal Life: 1_PRODUCTS/4_UNIVERSAL_LIFE.md
    - Investment Linked: 1_PRODUCTS/5_INVESTMENT_LINKED.md
  - Valuation: Placeholder.md
  - Solvency:
    - Risk Based Capital: 3_SOLVENCY/0_RISK_BASED_CAPITAL.md
  - Embedded Value: Placeholder.md
  - IFRS17: Placeholder.md
  - Distribution: Placeholder.md
  - Health Insurance: Placeholder.md
  - General Insurance: Placeholder.md

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_css:
  - config/extra.css

extra_javascript:
  - config/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js